void jack_bauer(void);
int print_last_digit(int n);
int _abs(int n);
int main(void);
void print_alphabet_x10(void);
void print_alphabet(void);
int _islower(int c);
int _isalpha(int c);
void _putchar(int n);
int print_sign(int n);
